import { Project, Freelancer, Testimonial } from "@/types/models";

export const mockProjects: Project[] = [
  {
    id: "1",
    title: "Application Mobile E-commerce",
    description: "Développement d'une application mobile complète pour une boutique en ligne avec paiement intégré et gestion des stocks.",
    budget: { min: 2000, max: 5000, currency: "GNF" },
    skills: ["React Native", "Node.js", "MongoDB"],
    proposalsCount: 12,
    duration: "2-3 mois",
    postedAt: "Il y a 2 heures",
    client: { name: "Mamadou Diallo", avatar: "", verified: true },
    status: "open",
  },
  {
    id: "2",
    title: "Site Vitrine Restaurant",
    description: "Création d'un site web moderne pour un restaurant avec menu en ligne, réservation et galerie photo.",
    budget: { min: 500, max: 1500, currency: "GNF" },
    skills: ["React", "Tailwind CSS", "Firebase"],
    proposalsCount: 8,
    duration: "2-4 semaines",
    postedAt: "Il y a 5 heures",
    client: { name: "Aissatou Barry", avatar: "", verified: true },
    status: "open",
  },
  {
    id: "3",
    title: "Dashboard Analytics",
    description: "Tableau de bord interactif pour la visualisation de données commerciales avec graphiques et rapports.",
    budget: { min: 3000, max: 7000, currency: "GNF" },
    skills: ["React", "D3.js", "Python", "PostgreSQL"],
    proposalsCount: 5,
    duration: "1-2 mois",
    postedAt: "Il y a 1 jour",
    client: { name: "Ibrahim Sow", avatar: "", verified: false },
    status: "open",
  },
  {
    id: "4",
    title: "Logo & Identité Visuelle",
    description: "Conception d'un logo professionnel et d'une charte graphique complète pour une startup tech.",
    budget: { min: 300, max: 800, currency: "GNF" },
    skills: ["Illustrator", "Photoshop", "Branding"],
    proposalsCount: 20,
    duration: "1-2 semaines",
    postedAt: "Il y a 3 heures",
    client: { name: "Fatoumata Camara", avatar: "", verified: true },
    status: "open",
  },
  {
    id: "5",
    title: "API REST pour Application Mobile",
    description: "Développement d'une API RESTful sécurisée pour une application mobile de livraison avec authentification JWT.",
    budget: { min: 1500, max: 4000, currency: "GNF" },
    skills: ["Node.js", "Express", "PostgreSQL", "Docker"],
    proposalsCount: 7,
    duration: "3-6 semaines",
    postedAt: "Il y a 6 heures",
    client: { name: "Ousmane Bah", avatar: "", verified: true },
    status: "open",
  },
  {
    id: "6",
    title: "Campagne Marketing Digital",
    description: "Stratégie et exécution d'une campagne de marketing digital complète incluant SEO, réseaux sociaux et email marketing.",
    budget: { min: 1000, max: 3000, currency: "GNF" },
    skills: ["SEO", "Google Ads", "Social Media", "Analytics"],
    proposalsCount: 15,
    duration: "1 mois",
    postedAt: "Il y a 12 heures",
    client: { name: "Mariama Keita", avatar: "", verified: true },
    status: "open",
  },
];

export const mockFreelancers: Freelancer[] = [
  {
    id: "1",
    name: "Abdoulaye Diallo",
    title: "Développeur Full Stack",
    avatar: "",
    rating: 4.9,
    reviewsCount: 47,
    hourlyRate: 35,
    currency: "USD",
    skills: ["React", "Node.js", "TypeScript", "MongoDB"],
    completedProjects: 52,
    location: "Conakry, Guinée",
    available: true,
    bio: "Développeur passionné avec 5+ ans d'expérience dans le développement web et mobile.",
  },
  {
    id: "2",
    name: "Kadiatou Bah",
    title: "Designer UI/UX",
    avatar: "",
    rating: 4.8,
    reviewsCount: 35,
    hourlyRate: 30,
    currency: "USD",
    skills: ["Figma", "Illustrator", "Photoshop", "Prototyping"],
    completedProjects: 38,
    location: "Conakry, Guinée",
    available: true,
    bio: "Créatrice d'expériences utilisateur intuitives et visuellement remarquables.",
  },
  {
    id: "3",
    name: "Mohamed Camara",
    title: "Développeur Mobile",
    avatar: "",
    rating: 4.7,
    reviewsCount: 28,
    hourlyRate: 40,
    currency: "USD",
    skills: ["React Native", "Flutter", "Swift", "Kotlin"],
    completedProjects: 31,
    location: "Conakry, Guinée",
    available: false,
    bio: "Spécialiste en développement d'applications mobiles cross-platform.",
  },
  {
    id: "4",
    name: "Fatoumata Sow",
    title: "Marketing Digital",
    avatar: "",
    rating: 4.9,
    reviewsCount: 42,
    hourlyRate: 25,
    currency: "USD",
    skills: ["SEO", "Google Ads", "Social Media", "Content"],
    completedProjects: 65,
    location: "Labé, Guinée",
    available: true,
    bio: "Experte en stratégies digitales qui génèrent des résultats mesurables.",
  },
  {
    id: "5",
    name: "Alpha Oumar Barry",
    title: "Développeur Backend",
    avatar: "",
    rating: 4.6,
    reviewsCount: 19,
    hourlyRate: 38,
    currency: "USD",
    skills: ["Python", "Django", "PostgreSQL", "Docker"],
    completedProjects: 22,
    location: "Kankan, Guinée",
    available: true,
    bio: "Architecte de systèmes robustes et scalables.",
  },
  {
    id: "6",
    name: "Mariama Touré",
    title: "Rédactrice Web",
    avatar: "",
    rating: 4.8,
    reviewsCount: 56,
    hourlyRate: 20,
    currency: "USD",
    skills: ["Copywriting", "SEO Writing", "Blogging", "Traduction"],
    completedProjects: 89,
    location: "Conakry, Guinée",
    available: true,
    bio: "Rédactrice créative spécialisée dans le contenu web engageant.",
  },
];

export const mockTestimonials: Testimonial[] = [
  {
    id: "1",
    name: "Mamadou Bah",
    role: "CEO, TechStart Guinea",
    avatar: "",
    content: "FreeJobGN a transformé la façon dont nous trouvons des talents. En quelques jours, nous avons trouvé le développeur parfait pour notre projet.",
    rating: 5,
  },
  {
    id: "2",
    name: "Aissatou Diallo",
    role: "Freelance Designer",
    avatar: "",
    content: "Grâce à FreeJobGN, j'ai pu développer ma carrière de freelance et travailler avec des clients incroyables en Guinée et à l'international.",
    rating: 5,
  },
  {
    id: "3",
    name: "Ibrahim Keita",
    role: "Directeur Marketing, AfricaConnect",
    avatar: "",
    content: "La qualité des freelancers sur cette plateforme est exceptionnelle. Nos projets sont livrés dans les temps et dépassent nos attentes.",
    rating: 5,
  },
];

export const stats = [
  { label: "Freelancers Actifs", value: 2500, suffix: "+" },
  { label: "Projets Complétés", value: 8000, suffix: "+" },
  { label: "Clients Satisfaits", value: 1200, suffix: "+" },
  { label: "Taux de Satisfaction", value: 98, suffix: "%" },
];
