import { Project, Freelancer, Testimonial } from "@/types/models";

export const mockProjects: Project[] = [
  {
    id: "1",
    title: "Application Mobile E-commerce",
    description: "Développement d'une application mobile complète pour une boutique en ligne avec paiement intégré et gestion des stocks.",
    budget: { min: 2000, max: 5000, currency: "GNF" },
    skills: ["React Native", "Node.js", "MongoDB"],
    proposalsCount: 12,
    duration: "2-3 mois",
    postedAt: "Il y a 2 heures",
    client: { name: "Mamadou Diallo", avatar: "/avatars/client-1.jpg", verified: true },
    status: "open",
  },
  {
    id: "2",
    title: "Site Vitrine Restaurant",
    description: "Création d'un site web moderne pour un restaurant avec menu en ligne, réservation et galerie photo.",
    budget: { min: 500, max: 1500, currency: "GNF" },
    skills: ["React", "Tailwind CSS", "Firebase"],
    proposalsCount: 8,
    duration: "2-4 semaines",
    postedAt: "Il y a 5 heures",
    client: { name: "Aissatou Barry", avatar: "/avatars/client-6.jpg", verified: true },
    status: "open",
  },
  {
    id: "3",
    title: "Dashboard Analytics",
    description: "Tableau de bord interactif pour la visualisation de données commerciales avec graphiques et rapports.",
    budget: { min: 3000, max: 7000, currency: "GNF" },
    skills: ["React", "D3.js", "Python", "PostgreSQL"],
    proposalsCount: 5,
    duration: "1-2 mois",
    postedAt: "Il y a 1 jour",
    client: { name: "Ibrahim Sow", avatar: "/avatars/client-8.jpg", verified: false },
    status: "open",
  },
  {
    id: "4",
    title: "Logo & Identité Visuelle",
    description: "Conception d'un logo professionnel et d'une charte graphique complète pour une startup tech.",
    budget: { min: 300, max: 800, currency: "GNF" },
    skills: ["Illustrator", "Photoshop", "Branding"],
    proposalsCount: 20,
    duration: "1-2 semaines",
    postedAt: "Il y a 3 heures",
    client: { name: "Fatoumata Camara", avatar: "/avatars/client-9.jpg", verified: true },
    status: "open",
  },
  {
    id: "5",
    title: "API REST pour Application Mobile",
    description: "Développement d'une API RESTful sécurisée pour une application mobile de livraison avec authentification JWT.",
    budget: { min: 1500, max: 4000, currency: "GNF" },
    skills: ["Node.js", "Express", "PostgreSQL", "Docker"],
    proposalsCount: 7,
    duration: "3-6 semaines",
    postedAt: "Il y a 6 heures",
    client: { name: "Ousmane Bah", avatar: "/avatars/client-2.jpg", verified: true },
    status: "open",
  },
  {
    id: "6",
    title: "Campagne Marketing Digital",
    description: "Stratégie et exécution d'une campagne de marketing digital complète incluant SEO, réseaux sociaux et email marketing.",
    budget: { min: 1000, max: 3000, currency: "GNF" },
    skills: ["SEO", "Google Ads", "Social Media", "Analytics"],
    proposalsCount: 15,
    duration: "1 mois",
    postedAt: "Il y a 12 heures",
    client: { name: "Mariama Keita", avatar: "/avatars/client-10.jpg", verified: true },
    status: "open",
  },
  {
    id: "7",
    title: "Plateforme de Réservation en Ligne",
    description: "Système de réservation pour hôtel avec gestion des chambres, paiements en ligne et tableau de bord administrateur.",
    budget: { min: 4000, max: 8000, currency: "GNF" },
    skills: ["Vue.js", "Laravel", "MySQL", "Stripe"],
    proposalsCount: 9,
    duration: "2-4 mois",
    postedAt: "Il y a 8 heures",
    client: { name: "Thierno Diallo", avatar: "/avatars/client-3.jpg", verified: true },
    status: "open",
  },
  {
    id: "8",
    title: "Application de Gestion Scolaire",
    description: "Logiciel complet pour gérer les élèves, notes, présences, et communication parents-professeurs.",
    budget: { min: 3500, max: 6500, currency: "GNF" },
    skills: ["Angular", "Spring Boot", "PostgreSQL"],
    proposalsCount: 6,
    duration: "3-5 mois",
    postedAt: "Il y a 1 jour",
    client: { name: "Hadja Binta Sow", avatar: "/avatars/client-7.jpg", verified: true },
    status: "open",
  },
  {
    id: "9",
    title: "Montage Vidéo Publicitaire",
    description: "Montage professionnel d'une vidéo publicitaire de 60 secondes avec effets spéciaux et motion design.",
    budget: { min: 400, max: 900, currency: "GNF" },
    skills: ["Premiere Pro", "After Effects", "Motion Design"],
    proposalsCount: 18,
    duration: "1-2 semaines",
    postedAt: "Il y a 4 heures",
    client: { name: "Alpha Condé", avatar: "/avatars/client-4.jpg", verified: false },
    status: "open",
  },
  {
    id: "10",
    title: "Refonte Site E-learning",
    description: "Modernisation complète d'une plateforme e-learning avec nouveau design, optimisation performance et nouvelles fonctionnalités.",
    budget: { min: 5000, max: 10000, currency: "GNF" },
    skills: ["React", "Next.js", "Prisma", "AWS"],
    proposalsCount: 4,
    duration: "3-6 mois",
    postedAt: "Il y a 2 jours",
    client: { name: "Naby Keita", avatar: "/avatars/client-5.jpg", verified: true },
    status: "open",
  },
  {
    id: "11",
    title: "Chatbot Service Client",
    description: "Développement d'un chatbot intelligent pour automatiser le service client avec IA et NLP.",
    budget: { min: 2500, max: 5500, currency: "GNF" },
    skills: ["Python", "TensorFlow", "Dialogflow", "Node.js"],
    proposalsCount: 11,
    duration: "2-3 mois",
    postedAt: "Il y a 10 heures",
    client: { name: "Sekou Touré", avatar: "/avatars/client-1.jpg", verified: true },
    status: "open",
  },
  {
    id: "12",
    title: "Design UI/UX Application Fintech",
    description: "Conception complète de l'interface utilisateur pour une application de paiement mobile avec prototypes interactifs.",
    budget: { min: 1800, max: 3500, currency: "GNF" },
    skills: ["Figma", "Sketch", "Prototyping", "User Research"],
    proposalsCount: 14,
    duration: "1-2 mois",
    postedAt: "Il y a 7 heures",
    client: { name: "Kaba Diawara", avatar: "/avatars/client-2.jpg", verified: true },
    status: "open",
  },
];

export const mockFreelancers: Freelancer[] = [
  {
    id: "1",
    name: "Abdoulaye Diallo",
    title: "Développeur Full Stack",
    avatar: "",
    rating: 4.9,
    reviewsCount: 47,
    hourlyRate: 35,
    currency: "USD",
    skills: ["React", "Node.js", "TypeScript", "MongoDB"],
    completedProjects: 52,
    location: "Conakry, Guinée",
    available: true,
    bio: "Développeur passionné avec 5+ ans d'expérience dans le développement web et mobile.",
  },
  {
    id: "2",
    name: "Kadiatou Bah",
    title: "Designer UI/UX",
    avatar: "",
    rating: 4.8,
    reviewsCount: 35,
    hourlyRate: 30,
    currency: "USD",
    skills: ["Figma", "Illustrator", "Photoshop", "Prototyping"],
    completedProjects: 38,
    location: "Conakry, Guinée",
    available: true,
    bio: "Créatrice d'expériences utilisateur intuitives et visuellement remarquables.",
  },
  {
    id: "3",
    name: "Mohamed Camara",
    title: "Développeur Mobile",
    avatar: "",
    rating: 4.7,
    reviewsCount: 28,
    hourlyRate: 40,
    currency: "USD",
    skills: ["React Native", "Flutter", "Swift", "Kotlin"],
    completedProjects: 31,
    location: "Conakry, Guinée",
    available: false,
    bio: "Spécialiste en développement d'applications mobiles cross-platform.",
  },
  {
    id: "4",
    name: "Fatoumata Sow",
    title: "Marketing Digital",
    avatar: "",
    rating: 4.9,
    reviewsCount: 42,
    hourlyRate: 25,
    currency: "USD",
    skills: ["SEO", "Google Ads", "Social Media", "Content"],
    completedProjects: 65,
    location: "Labé, Guinée",
    available: true,
    bio: "Experte en stratégies digitales qui génèrent des résultats mesurables.",
  },
  {
    id: "5",
    name: "Alpha Oumar Barry",
    title: "Développeur Backend",
    avatar: "",
    rating: 4.6,
    reviewsCount: 19,
    hourlyRate: 38,
    currency: "USD",
    skills: ["Python", "Django", "PostgreSQL", "Docker"],
    completedProjects: 22,
    location: "Kankan, Guinée",
    available: true,
    bio: "Architecte de systèmes robustes et scalables.",
  },
  {
    id: "6",
    name: "Mariama Touré",
    title: "Rédactrice Web",
    avatar: "",
    rating: 4.8,
    reviewsCount: 56,
    hourlyRate: 20,
    currency: "USD",
    skills: ["Copywriting", "SEO Writing", "Blogging", "Traduction"],
    completedProjects: 89,
    location: "Conakry, Guinée",
    available: true,
    bio: "Rédactrice créative spécialisée dans le contenu web engageant.",
  },
  {
    id: "7",
    name: "Ibrahima Konaté",
    title: "Data Scientist",
    avatar: "",
    rating: 4.9,
    reviewsCount: 31,
    hourlyRate: 45,
    currency: "USD",
    skills: ["Python", "Machine Learning", "TensorFlow", "SQL"],
    completedProjects: 27,
    location: "Conakry, Guinée",
    available: true,
    bio: "Expert en intelligence artificielle et analyse de données complexes.",
  },
  {
    id: "8",
    name: "Aissatou Diallo",
    title: "Chef de Projet Digital",
    avatar: "",
    rating: 4.7,
    reviewsCount: 44,
    hourlyRate: 32,
    currency: "USD",
    skills: ["Agile", "Scrum", "Jira", "Management"],
    completedProjects: 58,
    location: "Conakry, Guinée",
    available: true,
    bio: "Gestion de projets digitaux avec méthodologies agiles et livraison garantie.",
  },
  {
    id: "9",
    name: "Sekou Bangoura",
    title: "Développeur WordPress",
    avatar: "",
    rating: 4.6,
    reviewsCount: 67,
    hourlyRate: 22,
    currency: "USD",
    skills: ["WordPress", "PHP", "WooCommerce", "Elementor"],
    completedProjects: 94,
    location: "Labé, Guinée",
    available: true,
    bio: "Spécialiste WordPress avec expertise en e-commerce et optimisation SEO.",
  },
  {
    id: "10",
    name: "Nènè Sylla",
    title: "Graphiste & Illustratrice",
    avatar: "",
    rating: 4.8,
    reviewsCount: 52,
    hourlyRate: 28,
    currency: "USD",
    skills: ["Illustrator", "Photoshop", "InDesign", "Branding"],
    completedProjects: 71,
    location: "Conakry, Guinée",
    available: true,
    bio: "Création d'identités visuelles uniques et illustrations sur mesure.",
  },
  {
    id: "11",
    name: "Mamadou Lamarana Bah",
    title: "Développeur Laravel",
    avatar: "",
    rating: 4.7,
    reviewsCount: 38,
    hourlyRate: 35,
    currency: "USD",
    skills: ["Laravel", "PHP", "Vue.js", "MySQL"],
    completedProjects: 45,
    location: "Kankan, Guinée",
    available: false,
    bio: "Expert Laravel pour applications web robustes et évolutives.",
  },
  {
    id: "12",
    name: "Hawa Baldé",
    title: "Community Manager",
    avatar: "",
    rating: 4.9,
    reviewsCount: 61,
    hourlyRate: 24,
    currency: "USD",
    skills: ["Social Media", "Content Creation", "Canva", "Analytics"],
    completedProjects: 103,
    location: "Conakry, Guinée",
    available: true,
    bio: "Animation de communautés engagées et création de contenu viral.",
  },
  {
    id: "13",
    name: "Thierno Amadou Diallo",
    title: "Développeur Flutter",
    avatar: "",
    rating: 4.8,
    reviewsCount: 29,
    hourlyRate: 42,
    currency: "USD",
    skills: ["Flutter", "Dart", "Firebase", "REST API"],
    completedProjects: 34,
    location: "Conakry, Guinée",
    available: true,
    bio: "Applications mobiles performantes avec Flutter et design moderne.",
  },
  {
    id: "14",
    name: "Aminata Kourouma",
    title: "Traductrice Multilingue",
    avatar: "",
    rating: 4.7,
    reviewsCount: 48,
    hourlyRate: 18,
    currency: "USD",
    skills: ["Français", "Anglais", "Pulaar", "Soussou"],
    completedProjects: 127,
    location: "Labé, Guinée",
    available: true,
    bio: "Traduction professionnelle FR/EN et langues locales guinéennes.",
  },
  {
    id: "15",
    name: "Ousmane Conté",
    title: "Expert Cybersécurité",
    avatar: "",
    rating: 4.9,
    reviewsCount: 23,
    hourlyRate: 55,
    currency: "USD",
    skills: ["Security", "Penetration Testing", "Linux", "Networking"],
    completedProjects: 19,
    location: "Conakry, Guinée",
    available: true,
    bio: "Sécurisation d'infrastructures et audits de sécurité complets.",
  },
  {
    id: "16",
    name: "Djénabou Soumah",
    title: "Monteuse Vidéo",
    avatar: "",
    rating: 4.8,
    reviewsCount: 55,
    hourlyRate: 26,
    currency: "USD",
    skills: ["Premiere Pro", "After Effects", "DaVinci Resolve"],
    completedProjects: 78,
    location: "Conakry, Guinée",
    available: true,
    bio: "Montage vidéo créatif pour publicités, clips et documentaires.",
  },
  {
    id: "17",
    name: "Alsény Cissé",
    title: "Consultant SEO",
    avatar: "",
    rating: 4.7,
    reviewsCount: 41,
    hourlyRate: 33,
    currency: "USD",
    skills: ["SEO", "Google Analytics", "SEMrush", "Content Strategy"],
    completedProjects: 62,
    location: "Conakry, Guinée",
    available: true,
    bio: "Optimisation SEO pour première page Google et trafic organique.",
  },
  {
    id: "18",
    name: "Binta Diakité",
    title: "Développeuse Angular",
    avatar: "",
    rating: 4.6,
    reviewsCount: 26,
    hourlyRate: 37,
    currency: "USD",
    skills: ["Angular", "TypeScript", "RxJS", "NgRx"],
    completedProjects: 29,
    location: "Kankan, Guinée",
    available: true,
    bio: "Applications web enterprise avec Angular et architecture scalable.",
  },
];

export const mockTestimonials: Testimonial[] = [
  {
    id: "1",
    name: "Mamadou Bah",
    role: "CEO, TechStart Guinea",
    avatar: "",
    content: "FreeJobGN a transformé la façon dont nous trouvons des talents. En quelques jours, nous avons trouvé le développeur parfait pour notre projet.",
    rating: 5,
  },
  {
    id: "2",
    name: "Aissatou Diallo",
    role: "Freelance Designer",
    avatar: "",
    content: "Grâce à FreeJobGN, j'ai pu développer ma carrière de freelance et travailler avec des clients incroyables en Guinée et à l'international.",
    rating: 5,
  },
  {
    id: "3",
    name: "Ibrahim Keita",
    role: "Directeur Marketing, AfricaConnect",
    avatar: "",
    content: "La qualité des freelancers sur cette plateforme est exceptionnelle. Nos projets sont livrés dans les temps et dépassent nos attentes.",
    rating: 5,
  },
];

export const stats = [
  { label: "Freelancers Actifs", value: 2500, suffix: "+" },
  { label: "Projets Complétés", value: 8000, suffix: "+" },
  { label: "Clients Satisfaits", value: 1200, suffix: "+" },
  { label: "Taux de Satisfaction", value: 98, suffix: "%" },
];
